baseurl = "https://blog.rayane.tech/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Guebre Nadir Rayane"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
[services.googleAnalytics]
ID = "G-FZRYFZYH3W"

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "Rayan"
description = "My personal blog"
avatar = "me/avatar.png"
headerTitle = "Rayan's Personal Blog"
# motto = ""

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

#valine = true
#LEANCLOUD_APP_ID = "kL1jt3N2rqSPorsuxupirium-MdYXbMMI"
#LEANCLOUD_APP_KEY = "rBvCFOVGqi7wU8J8ria9x2MI"

# waline = true
#walineServer = "https://waline-blog-wheat.vercel.app/"

email = "contact@rayane.tech"

siteStartYear = 2025

# favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
# showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

[params.navItems]
github = { href = "https://github.com/Rayanlupo", target = "_blank", icon = "logo-github", title = "GitHub" }


 [params.twikoo]
 enabled = true
 envID = "https://twikoo-blog-comments-mu.vercel.app"
 region = ""
 lang = "Vercel"

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"
